### ISSUE TITLE
[Checklist] 과제 제출 전 확인 내용

### ISSUE THREAD

**Issue by OZestina** [42Seoul-Tea42/matcha#3]
### General Instructions
- [x] error, warning, notice 없는지 확인했죠?
- [x] <del>security branch 안썼죠?</del> (No security breaches are allowed. ) 보안 위반사항은 허용되지 않습니다.
- [x] 프레임워크의 ORM, validators, User Account Manager 안썼죠?
- [ ] 최신 Chrome과 Firefox에서 잘 동작하죠?
- [x] header, main, footer로 구분된 레이아웃을 가지고 있죠?
- [ ] 모바일에서도 사용 가능하죠? (작은 화면에서도 괜찮은 레이아웃을 가지고 있죠?)
- 적절한 validation 처리를 했나요? 웹사이트가 보호되고 있나요?
    - [x] DB에 비밀번호 저장 시 암호화했나요?
    - [x] HTML injection, user JS code를 삽입허용하지 않았나요?
    - [x] 원하지 않은 콘텐츠의 업로드를 막았나요?
    - [x] SQL alteration을 막았나요?
- for security reasons
    - [x] any credentials, API keys, env variables, etc. 는 .env 파일 내에 보관하고 git에서는 제외해야합니다

### Registration and Signing-in
- [x] 유저 등록이 가능한가요?
- [x] 이메일 주소, 유저네임, 성, 이름, 비밀번호(protected)를 요청했나요?
- [x] 유저 등록 후 계정 확인을 위해 이메일로 확인 링크(unique link)가 전달됐나요?
- [x] 유저네임, 비밀번호로 로그인 할 수 있나요?
- [x] 비밀번호를 잊어버렸을 때 재설정할 수 있는 메일을 보내주나요?
- [x] 사이트의 어디서든 한 번의 클릭으로 로그아웃 할 수 있나요?

### User profile
- 유저가 등록 및 확인되면 프로필 작성을 하나요?
    - [x] 성별
    - [x] 성적 취향 (Sexual preferences)
    - [x] 자기소개 (a biography)
    - [x] 취미/취향/흥미 관련 태크(tags)
    - [x] (최대 5장의) 사진, 그 중 한 장은 프로필 사진으로 사용
- [x] (at any time) 유저가 프로필 내용을 변경할 수 있나요?
    - [x] 위의 프로필 작성 내용
    - [x] 성, 이름, 이메일 주소
    - [x] GPS position
- [x] 유저가 자신의 프로필을 확인한 사람을 확인할 수 있나요?
- [x] 유저가 자신을 "fancy"한 사람을 확인할 수 있나요?
- [x] (public) fame rating이 있나요?
- [x] GPS를 이용해 유저의 위치를 확인하나요?
    - [x] 유저가 위치 확인을 거절했을 때, 위치를 확인할 수 있는 방법을 찾았나요?

### Browsing (추천받기)
- 유저는 자신의 프로필과 매칭되는 제안을 쉽게 확인할 수 있어야 합니다
- [x] 적합한("interesting") 프로필만 보여주나요?
    - [x] 유저의 성별이 특정되지 않은 경우 bisexual로 처리했나요?
    - [x] (서로의) 성적 취향을 충족하는 프로필만 보여주나요?
- 매치 조건에 따라 제안하나요?
    - [x] 유저와 같은 지역 (same geographic area)
    - [x] 공통된 관심사 (common tags)
    - [x] maximum "fame rating"
- [x] 같은 지역의 프로필을 우선순위로 보여주나요?
- [x] 리스트가 나이, 위치, fame rating, 관심사에 따라 정렬되나요? (sortable)
- [x] 리스트가 나이, 위치, fame rating, 관심사에 따라 필터되나요? (filterable)

### Research (검색)
- 유저는 하나 이상의 조건을 걸어서 프로필을 검색할 수 있어야 합니다
    - [x] 나이 차
    - [x] fame rating 차
    - [x] 지역
    - [x] 하나 이상의 관심사 (interest tags)
- [x] 검색결과가 나이, 위치, fame rating, 관심사에 따라 정렬되나요? (sortable)
- [x] 검색결과가 나이, 위치, fame rating, 관심사에 따라 필터되나요? (filterable)

### Profile of other users
- [x] 다른 유저의 프로필을 볼 수 있나요?
- [x] 이메일 주소, 비밀번호 외의 다른 모든 정보를 확인할 수 있나요?
- [x] 다른 유저의 프로필을 확인하면, 유저의 visit history에 추가되나요?
- [x] 다른 유저의 프로필 "사진"을 "fancy"할 수 있나요?
    - [x] 두 유저가 서로 "fancy"했을 때, "connected"돼 채팅을 시작할 수 있나요?
    - [x] 프로필 사진이 없으면 이 내용을 실행할 수 없어야 합니다
- [x] "fancy"를 취소할 수 있나요?
    - [x] "fancy"를 취소하면 관련된 알람이 더 이상 오지 않아야해요
    - [x] "connected"된 유저의 "fancy"를 취소하면 그 유저와 더 이상 채팅을 할 수 없어야해요
- [x] 다른 유저의 "fame rating"을 확인할 수 있나요?
- [x] 유저가 현재 온라인 상태인지 확인할 수 있나요?
    - [x] 현재 온라인이 아니라면, 가장 최근에 접속한 기록(날짜, 시간)을 보여줘야해요
- [x] 가짜 계정이 의심되는 유저를 "report"할 수 있나요?
- [x] 유저를 "block"할 수 있나요?
    - [x] 내가 blocked user는 추천/검색 결과에서 나오지 않아야 해요
    - [x] 내가 blocked user와 관련된 추가적인 알람을 받지 않아야 해요
    - [x] 내가 blocked user와는 더 이상 채팅을 할 수 없어요
- [x] 유저가 보고있는 프로필과 "connected"된 상태인지 명확히 알 수 있나요?
- [x] 유저가 보고있는 프로필이 유저를 "fancy"했는지 명확히 알 수 있나요?
- [x] 보고있는 프로필에서 "fancy"를 취소할 수 있나요? (unlike or disconnect)

### Chat
- 두 유저가 connect 됐을 때 실시간으로 채팅을 할 수 있어야 합니다
- [x] connect 된 유저들 끼리만 채팅이 가능해야해요
- [x] 실시간으로 채팅이 가능한가요? (최대 딜레이 10초)
- [x] 새로운 메시지가 왔을 때 페이지의 어디에 있든 알람을 확인할 수 있나요?

### Notifications
- 하기의 이벤트의 경우 실시간(최대 딜레이 10초)으로 알람을 받아야 합니다
    - [x] 새로운 "fancy"를 받았을 때 -> 팬시 탭
    - [x] 다른 유저가 자신의 프로필을 확인했을 때 -> 팬시 탭
    - [x] 새로운 메시지를 받았을 때 -> 채팅 탭
    - [x] 자신이 "fancy"한 유저가 "fancy-back"했을 때 (새로 connect 됐을 때) -> 채팅 탭
    - [x] connect된 유저가 "un-fancy"했을 때 (connect 끊어졌을 떄) -> 채팅 탭
- [x] 유저가 어떤 페이지에 있든지 알람을 확인할 수 있어야 합니다

### In case of BONUS
- [ ] Omniauth strategies
- [ ] SNS에서 사진 가져오기
- [ ] user의 interactive map 개발
- [ ] connect된 유저들을 위해 video 혹은 audio 챗 제공
- [ ] match된 유저들을 위해 실제 날짜, 이벤트를 예약하는 기능 제공

**Comment by JaeJunday** [comment]
과제 오역이 있어서 수정했습니다. 
branch -> breaches 
No security breaches are allowed.
